# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b44a3732ee729c3f9228e91730c025bb4fac53ed1300aca108d75a556bb86d299216b271c575068edf41d96a69dcf0679370b11e502a55b2fe1346c7adfecda

test:
  secret_key_base: e4e6696b710b538b3e462b45223f53f3a5cd750a1671e1334bdf806f30d5401c4b6d4d1b0755b43e9c1a21d985124009a5e62d58f9d1a15ace73476c3c16c837

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
